POPR-164: Added add slide button to editor view component
AgusPk/meethead pull request #18
Opened 2022-09-13 19:38 UTC by maruPortal

# Related Task
- https://app.clickup.com/t/459857/POPR-164

# Proposed Changes
- created generalIconButton on UI
- Added button on editor view component
- When clicking on that button a slide is added to an array of slides

# Additional Info (Optional)
- 

# How to test this?
- click on the add slide button

# Task Checklist
- [ ] All new features have been documented
- [ ] Conventions and Acceptance criteria have been met
- [ ] Code is free of warnings
- [ ] ClickUp task has been set to Awaiting Review

2022-09-14 12:20 UTC, rosariosm requested changes

2022-09-14 12:20 UTC, rosariosm commented on frontend/app/src/layouts/PreviewLayout/index.tsx
> +  const showSlides = () => {
Move this to a  component called SlideList. You can define it in app project.  Move all Slide logic to that componenr

2022-09-14 12:20 UTC, rosariosm commented on frontend/ui/src/components/GeneralIconButton/styles.ts
> +  box-shadow: 0px 3px 5px -1px rgba(0, 0, 0, 0.2),
I don't think you need to redefine all this styles. All you need to do is use IconButton size='large' and set background color from theme :)

2022-09-14 12:20 UTC, rosariosm commented on frontend/ui/src/components/GeneralIconButton/styles.ts
> +  &:hover {
Would you mind adding a Material ui theme and edit colors there? I can help you if you need it

2022-09-14 12:59 UTC, rosariosm commented on frontend/ui/src/components/GeneralIconButton/styles.ts
> +  &:hover {
Talk to Pam because I think she was implementing it, but I'm not sure

2022-09-15 14:15 UTC, AgusPk approved these changes

2022-09-15 14:34 UTC, merged